name: Spring Boot CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Create application.properties
        run: |
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> question/src/main/resources/application.properties
          echo "spring.datasource.url=jdbc:mysql://${{ secrets.HONGSAMSTICK_DB_HOST }}:3306/${{ secrets.HONGSAMSTICK_DB_NAME }}" >> question/src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.HONGSAMSTICK_DB_USERNAME }}" >> question/src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.HONGSAMSTICK_DB_PASSWORD }}" >> question/src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> question/src/main/resources/application.properties
          echo "spring.mvc.hiddenmethod.filter.enabled=true" >> question/src/main/resources/application.properties
          echo "spring.mail.host=${{ secrets.HONGSAMSTICK_MAIL_HOST }}" >> question/src/main/resources/application.properties
          echo "spring.mail.port=${{ secrets.HONGSAMSTICK_MAIL_PORT }}" >> question/src/main/resources/application.properties
          echo "spring.mail.username=${{ secrets.HONGSAMSTICK_MAIL_USERNAME }}" >> question/src/main/resources/application.properties
          echo "spring.mail.password=${{ secrets.HONGSAMSTICK_MAIL_PASSWORD }}" >> question/src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.auth=true" >> question/src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.starttls.enable=true" >> question/src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.starttls.required=true" >> question/src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.ssl.trust=${{ secrets.HONGSAMSTICK_MAIL_HOST }}" >> question/src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.ssl.enable=true" >> question/src/main/resources/application.properties
          echo "spring.mail.default-encoding=UTF-8" >> question/src/main/resources/application.properties
      - name: Build with Gradle
        run: ./question/gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar
    
  # 도커 허브에 이미지를 푸시하는 작업

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./question
          file: ./question/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hongsamstick:springboot

  # ec2 서버에 접속

  ec2:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
  # 도커 허브에서 이미지 pull
  docker:
    needs: ec2
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hongsamstick:springboot
      - name: Stop existing container
        run: docker stop myapp || true
      - name: Run Docker container
        run: docker run -d --rm --name myapp -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/hongsamstick:springboot
